<?php

$title = "Erreur-Le café du Dev";

ob_start(); ?>

<h2>Oops Une erreur est survenue !</h2>
<div class='error'>
    <h3><?=$errorTitle?></h3>
    <img src="public/assets/img/<?=$errorImg?>.jpg" alt="image erreur" class="error_img">
    <?php 
    if(isset($errorMessage)): ?>
    <p><?= $errorMessage ?></p>
    <?php endif ?>
    
    
    
</div>

<?php
$content = ob_get_clean(); 

require 'template.phtml';