<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title><?= $title ?></title>
    <link href="https://fonts.googleapis.com/css?family=Lacquer|Open+Sans|Pacifico&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="public/assets/css/style.css">
    <script src="https://kit.fontawesome.com/635a5e5829.js"></script>
</head>
<body>
    <header>
        <h1 id="main_title"><a href='index.php?action=home'><i class="fas fa-mug-hot"></i> Le café du DEV <i class="fas fa-chalkboard-teacher"></i></a></h1>
        <nav>
            <ul>
            <!-- not connected -->
            <?php if (!isset($_SESSION['user'])) : ?>
                <li><a href="index.php?action=signIn"><i class="fas fa-door-open"></i> Connexion</a></li>
                <li><a href="index.php?action=signUp"><i class="fas fa-handshake"></i> Inscription</a></li>

            <?php else : 

                // admin connected
                if (isset($_SESSION['user']['role']) && $_SESSION['user']['role'] === 'admin') : ?>
                <li><a href="index.php?action=account&id=<?= $_SESSION['user']['id']?>"><i class="fas fa-user-cog"></i> Administration</a></li>
                <li><a href="index.php?action=logOut"><i class="fas fa-door-closed"></i> Déconnexion</a></li>

                <!-- user connected -->
                <?php else : ?>
                <li><a href="index.php?action=account&id=<?= $_SESSION['user']['id']?>"><i class="fas fa-user"></i> Mon compte</a></li>
                <li><a href="index.php?action=logOut"><i class="fas fa-door-closed"></i> Déconnexion</a></li>
                <?php endif ?>
                
            <?php endif ?>
                <li><a href="index.php?action=chat"><i class="fab fa-rocketchat"></i> Discuter en direct</a></li>
            </ul>

            <!-- informative message user or admin connected -->
            <?php if ( isset($_SESSION['user']) && $_SESSION['user']['role'] == 'admin'  ) : ?>
            <span class="user_role">Admin connecté : <?= $_SESSION['user']['pseudo'] ?> </span>
            <?php endif ?>
            <?php if( isset($_SESSION['user']) && $_SESSION['user']['role'] == 'user') : ?>
            <span class="user_role">Utilisateur connecté : <?= $_SESSION['user']['pseudo'] ?> </span>
            <?php endif ?>
        </nav>
    </header>
    
    <main class='container'>
        <?= $content ?>
    </main>
    <footer>
    <small> <em>&copy le café du Dev réalisé avec douceur et <span>caféine</span></em>  </small>
    <small><a href="#main_title">Haut de page</a></small>
    </footer>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="public/assets/js/ajax.js"></script>
    <script src="public/assets/js/events/eventsComment.js"></script>
    <script src="public/assets/js/events/eventsChat.js"></script>
    <script src="public/assets/js/events/eventsSignUp.js"></script>
    <script src="public/assets/js/events/eventsSignIn.js"></script>
    <script src="public/assets/js/events/eventsPost.js"></script>
    <script src="public/assets/js/main.js"></script>
</body>
</html>