<?php


$title = "Commentaires-Le café du Dev";

ob_start(); ?>

<h2><i class="fab fa-hotjar"></i> Discussion sur le sujet "<?= $post[0]->title ?>" </h2>
<!-- POST -->
<article class="postwithcomments">
    <h3><?= $post[0]->title ?> <span class='author_infos'>par <span class='touppercase'><?= $post[0]->pseudo ?></span> le <?= $post[0]->creation_date->format('d-m-Y à H:i') ?></span></h3>
    <p> <?= $post[0]->post ?> </p>
</article>
<!-- COMMENTAIRES -->
<div class="comment">
    <h2><i class="fas fa-comments"></i> Commentaires</h2>
    
    <?php
    foreach($comments as $comment): ?>
    <p><i class="fas fa-comment-dots"></i> <?= $comment->comment ?> <span class="infos_comment">par <?= $comment->author ?> le <?= $comment->creation_date->format('d-m-Y à H:i') ?></span></p>
    <?php endforeach ?>

<!-- FORM -->
    <form action="index.php?action=addComment&id=<?=$post[0]->id?>" method="POST" id="formComments">
        <fieldset>
            <legend><i class="fas fa-comment"></i> Participer à la discussion</legend>
            <p>
                <label for="author">Auteur :</label>
                <input id="author" name="author" type="text" placeholder="Votre nom: * " value="<?php $value = isset($_COOKIE['author']) ? htmlentities($_COOKIE['author']) : ''; echo $value  ?>" />
            </p>
            <p>
                <label for="message">Message :</label>
            <?php
                if (isset($_GET['error']) && $_GET['error'] == 1) : ?>
                <textarea id="message" name="message" type="text" placeholder="Votre message: *" ><?php $value = isset($_SESSION['comments']) ? htmlentities($_SESSION['comments']['message']) : ''; echo $value ?></textarea>
                <?php else : ?> 
                <textarea id="message" name="message" type="text" placeholder="Votre message: *"></textarea>
            <?php endif ?>
            </p>
            <span class='required_field'>* Champs obligatoires</span>
            <input type="submit" value="Envoyer" id="send_comment">
            <?php 
                if (isset($_GET['error']) && $_GET['error'] == 1) : 
                $errorsList = unserialize($_GET['errorslist']);
            ?>
            <div class="popup_error_form">
                <span>Envoi impossible veuillez vérifier les champs suivants :
                </span>
                <ul>
                    <?php 
                    foreach ($errorsList as $errorField) {
                        foreach ($errorField as $error ) { ?>
                            <li><?= $error ?></li>
                        <?php }
                    } ?>
                </ul>
            </div>
            <?php endif ?>
        </fieldset>
    </form>
</div>


<?php $content = ob_get_clean(); ?>

<?php require 'public/views/template.phtml'; ?>