<?php

$title = "Modifier un billet-Le café du Dev";

ob_start(); ?>

<form action="index.php?action=editPost&id=<?=$_GET['id']?>" method="POST">
    <fieldset>
        <legend>Modifier un billet</legend>
        <p>
            <label for="title">Titre</label>
            <input type="text" id='title' name='title' value='<?= $post[0]->title ?? "" ?>'>
        </p>
        <p>
            <label for="post"></label>
            <textarea name="post" id="post"><?= $post[0]->post ?? "" ?> </textarea>
        </p>
        <input type="submit">
        <?php 
            if (isset($_GET['error']) && $_GET['error'] == 1) : 
            $errorsList = unserialize($_GET['errorslist']);
        ?>
        <div class="popup_error_form">
            <span>Envoi impossible veuillez vérifier les champs suivants :
            </span>
            <ul>
                <?php 
                foreach ($errorsList as $errorField) {
                    foreach ($errorField as $error ) { ?>
                        <li><?= $error ?></li>
                    <?php }
                } ?>
            </ul>
        </div>
        <?php endif ?>
    </fieldset>
</form>

<?php $content = ob_get_clean(); 

require 'public/views/template.phtml'; ?>