<?php

$title = "Accueil-Le café du Dev";

ob_start(); ?>

<h2><i class="fab fa-hotjar"></i> Les derniers billets :</h2>

<?php
foreach($posts as $post) :?>
<article>
    <h3><?= $post->title ?></h3>
    <p><?= $post->post ?></p>
    <div>
        <h4><i class="fas fa-comment"></i> Derniers commentaires</h4>
        <p>Extrait de comm...</p>
    </div>
    <a href="">Voir ou ajouter un commentaire</a>
</article>
<?php endforeach ?>



<?php $content = ob_get_clean(); ?>

<?php require 'public/views/template.phtml'; ?>