<?php

$title = "Accueil-Le café du Dev";

ob_start(); ?>

<h2><i class="fab fa-hotjar"></i> Les derniers billets :</h2>

<?php
foreach($posts as $post) :?>
<!-- POSTS -->
<article>
    <h3><?= $post->title ?> <span class='author_infos'>par <span class='touppercase'><?= $post->pseudo ?></span> le <?= $post->creation_date->format('d-m-Y à H:i') ?></span></h3>
    <p><?= $post->post ?> </p>
    <div>
        <h4><i class="fas fa-comments"></i> Derniers commentaires</h4>

        <!-- 4 DERNIERS COMMENTAIRES -->
        <?php 
        $lastComments = $commentModel->getLastComments($post->id);

        foreach ($lastComments as $lastComment) : ?>
            <p class="last_comments"><i class="fas fa-comment-dots"></i> <?= $lastComment->getExcerpt() ?> <span class="infos_comment">par <?= $lastComment->author ?> le <?= $lastComment->creation_date->format('d-m-Y à H:i') ?></span></p>
        <?php endforeach ?>
    </div>
    <a href="index.php?page=comments&id=<?=$post->id?>">Voir la discussion complète ou ajouter un commentaire</a>

</article>
<?php endforeach ?>

<?php $content = ob_get_clean(); ?>

<?php require 'public/views/template.phtml'; ?>