<?php


$title = "Connexion-Le café du Dev";

ob_start(); ?>

<form action="index.php?action=logIn" method="POST" id="formSignIn">
        <fieldset>
            <legend><i class="fas fa-door-open"></i> Se connecter</legend>
            <p>
                <label for="email">Email :</label>

                <?php if (isset($_GET['error']) && $_GET['error'] == 1) : ?>

                <input id="email" name="email" type="email" placeholder="Votre mail: * " value="<?php $value = isset($_COOKIE['email']) ? htmlentities($_COOKIE['email']) : ''; echo $value  ?>" />

                <?php else : ?>

                <input id="email" name="email" type="email" placeholder="Votre mail: * " value ="<?php $value = isset($_COOKIE['author']) ? htmlentities($_COOKIE['email']) : ''; echo $value  ?>" />

                <?php endif ?>
            </p>
            <p>
                <label for="password">Mot de passe :</label>
                <input id="password" name="password" type="password" placeholder="Votre mot de passe: *" />
            </p>
            <span class='required_field'>* Champs obligatoires</span>
            <input type="submit" value="Connexion" id="send_signIn">

            <?php 
                if (isset($_GET['error']) && $_GET['error'] == 1) : 
                $errorsList = unserialize($_GET['errorslist']);
            ?>
            <div class="popup_error_form">
                <span>Envoi impossible veuillez vérifier les champs suivants :
                </span>
                <ul>
                    <?php 
                    foreach ($errorsList as $errorField) {
                        foreach ($errorField as $error ) { ?>
                            <li><?= $error ?></li>
                        <?php }
                    } ?>
                </ul>
            </div>
            <?php endif ?>
        </fieldset>
    </form>

<?php $content = ob_get_clean(); ?>

<?php require 'public/views/template.phtml'; ?>