<?php


$title = "Connexion-Le café du Dev";

ob_start(); ?>

<form action="index.php?action=logIn" method="POST" id="formSignIn">
        <fieldset>
            <legend><i class="fas fa-door-open"></i> Se connecter</legend>
            <p>
                <label for="email">Email :</label>
                <input id="email" name="emailSignIn" type="email" placeholder="Votre mail: * " value="<?php $value = isset($_COOKIE['email']) ? htmlspecialchars($_COOKIE['email']) : ''; echo $value  ?>" />
            </p>
            <p>
                <label for="password">Mot de passe :</label>
                <input id="password" name="password" type="password" placeholder="Votre mot de passe: *" />
            </p>
            <span class='required_field'>* Champs obligatoires</span>
            <input type="submit" value="Connexion" id="send_signIn">
            
            <!-- ERRORS -->
            <?php 
                if ( isset($_SESSION['userSignIn']['errors']) ) : 
                $errorsList = $_SESSION['userSignIn']['errors'];
            ?>
            <div class="popup_error_form">
                <span>Envoi impossible veuillez vérifier les champs suivants :
                </span>
                <ul>
                    <?php 
                    foreach ($errorsList as $errorField) {
                        foreach ($errorField as $error ) { ?>
                            <li><?= htmlspecialchars($error) ?></li>
                        <?php }
                    } 
                    unset($_SESSION['userSignIn']['errors']) 
                    ?>
                </ul>
            </div>
            <?php endif ?>
        </fieldset>
    </form>

<?php $content = ob_get_clean(); ?>

<?php require 'public/views/template.phtml'; ?>