<?php


$title = "Compte-Le café du Dev";

ob_start(); ?>

<h2><i class="fas fa-user"></i> Mon compte</h2>
<section id="user_infos" class="account_sections">
    <fieldset>
        <legend><i class="fas fa-user-secret"></i> Mes informations personnelles</legend>
        <p>
            <span class='label_infos'>Nom et prénom :</span> <?= $_SESSION['user']['lastName'] ." ". $_SESSION['user']['firstName'] ?>
        
        </p>
        <p><span class='label_infos'>Pseudo :</span> <?= $_SESSION['user']['pseudo'] ?></p>
        <p><span class='label_infos'>Email :</span> <?= $_SESSION['user']['email'] ?></p>
        <p><span class='label_infos'>Rang :</span> <?= $_SESSION['user']['role'] ?></p>
        <p><span class='label_infos'>Date inscription :</span> <?= $_SESSION['user']['datesub']->format('d-m-Y') ?></p>
        <!-- <p><a href="#">Changer de mot de pase</a></p> -->
    </fieldset>
</section>
<section id="user_posts" class="account_sections">
    <fieldset>
        <legend><i class="fas fa-pen-fancy"></i> Mes billets</legend>
        <?php if(!empty($userPosts)) : ?> 
    <table>
        <thead>
            <tr>
                <th>Id</th>
                <th>Titre</th>
                <th>Post</th>
                <th id="userPostsDate_th">Date de publication</th>
                <th id="updatePost_th">
                    <span class="updatePost_span">Modifier</span>
                    <span id="updatePost_separator">/</span>
                    <span class="updatePost_span">Supprimer</span>
                </th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($userPosts as $post): ?>
                <tr>
                    <td><?= $post->id ?></td>
                    <td><a href="index.php?id=<?= $post->id ?>&action=comments" target="_blank"><?= $post->title ?></a></td>
                    <td><?= $post->getExcerpt() ?></td>
                    <td class="userPostsDate_td"><?= $post->creation_date->format("d-m-Y")  ?></td>
                    <td>
                        <a class="edit" href="index.php?id=<?= $post->id ?>&action=editPostView"><i class="fas fa-pencil-alt"></i></a>
                        <a class="remove" href="index.php?id=<?= $post->id ?>&action=removePost"><i class="fas fa-trash-alt"></i></a>
                    </td>
                </tr>
            <?php endforeach ?>
            <tr>
                <td colspan="5" class="td_newpost"><a href='index.php?id=<?=$_SESSION['user']['id']?>&action=addPostView'><i class="fas fa-pen-fancy"></i> Rédiger un nouveau billet</a></td>
            </tr>
        </tbody>
    </table>
    <?php else : ?>
    <p><i class="far fa-frown"></i> Aucun billet écrit... N'hésitez pas à en <a href='index.php?id=<?=$_SESSION['user']['id']?>&action=addPostView'>rédiger</a> dès maintenant !</p>
    <?php endif ?>
    </fieldset>
</section>

<!-- ADMIN -->
<?php if ($_SESSION['user']['role'] === 'admin') : ?>

    <section id="user_all_posts" class="account_sections">
    <fieldset>
        <legend><i class="fas fa-pen-fancy"></i> Billets utilisateurs</legend>
        <?php if(!empty($posts)) : ?> 
    <table>
        <thead>
            <tr>
                <th>Id</th>
                <th>Auteur</th>
                <th>Titre</th>
                <th id="listAllPosts_th">Post</th>
                <th id="listAllPostsDate_th">Date de publication</th>
                <th>Supprimer</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($posts as $post): ?>
                <tr>
                    <td><?= $post->id ?></td>
                    <td><?= $post->pseudo ?></td>
                    <td><a href="index.php?id=<?= $post->id ?>&action=comments" target="_blank"><?= $post->title ?></a></td>
                    <td class="listAllPosts_td"><?= $post->getExcerpt() ?></td>
                    <td class="listAllPostsDate_td"><?= $post->creation_date->format("d-m-Y")  ?></td>
                    <td>
                        <a class="remove" href="index.php?id=<?= $post->id ?>&action=removePost"><i class="fas fa-trash-alt"></i></a>
                    </td>
                </tr>
            <?php endforeach ?>
        </tbody>
    </table>
    <?php else : ?>
    <p><i class="far fa-frown"></i> Aucun billet pour le moment
    <?php endif ?>
    </fieldset>
    </section>

    
    <section id="user_list" class="account_sections">
    <fieldset>
        <legend><i class="fas fa-user"></i> Utilisateurs</legend>
        <?php if(!empty($users)) : ?> 
    <table>
        <thead>
            <tr>
                <th>Id</th>
                <th id="userListNames_th"><span>Nom</span><span id="userListNames_separator">/</span><span>Prénom</span></th>
                <th id="userListMail_th">Email</th>
                <th>Pseudo</th>
                <th id="userListDate_th">Création</th>
                <th>Rang</th>
                <th>Supprimer</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($users as $user): ?>
                <tr>
                    <td><?= $user->id ?></td>
                    <td class="userListNames_td"><?= $user->lastname ." ". $user->firstname ?></td>
                    <td class="userListMail_td"><?= $user->email ?></td>
                    <td><?= $user->pseudo ?></td>
                    <td class="userListDate_td"><?= $user->subscription_date->format("d-m-Y")  ?></td>
                    <td>
                        <form action="index.php?action=editUser&id=<?= $user->id ?>" method="POST" id="user_form">
                            <select name="role">
                                <option value="user" <?php if($user->role === 'user') : echo 'selected'; endif ?> >Utilisateur</option>
                                <option value="admin" <?php if($user->role === 'admin') : echo 'selected'; endif ?>>Admin</option>
                            </select>
                            <button type="submit"><i class="fas fa-exchange-alt" title="changer"></i></button>
                        </form>
                    </td>
                    <td><a class="remove" href="index.php?id=<?= $user->id ?>&action=removeUser"><i class="fas fa-trash-alt"></i></a></td>
                </tr>
            <?php endforeach ?>
        </tbody>
    </table>
    <?php else : ?>
    <p><i class="far fa-frown"></i> Aucun utilsateur inscrit pour le moment</p>
    <?php endif ?>
    </fieldset>
</section>

<?php endif ?>
<!-- END ADMIN AREA -->


<?php $content = ob_get_clean(); ?>


<?php require 'public/views/template.phtml'; ?>