<?php

$title = "Rédiger un billet-Le café du Dev";

ob_start(); ?>

<form action="index.php?action=addPost&id=<?=$_GET['id']?>" method="POST">
    <fieldset>
        <legend>Rédiger un billet</legend>
        <p>
            <label for="title">Titre</label>
            <input type="text" id='title' name='title' placeholder="Titre du billet : *" value="<?php $value = isset($_SESSION['userAddPost']) ? $_SESSION['userAddPost']['title'] : ''; echo $value  ?>">
        </p>
        <p>
            <label for="post"></label>
            <textarea name="post" id="post" placeholder="Votre billet: *"><?php $value = isset($_SESSION['userAddPost']) ? $_SESSION['userAddPost']['post'] : ''; echo $value  ?></textarea>
        </p>
        <span class='required_field'>* Champs obligatoires</span>
        <input type="submit">
        
        <!-- ERRORS -->
        <?php 
            if ( isset($_SESSION['userAddPost']['errors']) ) : 
            $errorsList = $_SESSION['userAddPost']['errors'];
        ?>
        <div class="popup_error_form">
            <span>Envoi impossible veuillez vérifier les champs suivants :
            </span>
            <ul>
                <?php 
                foreach ($errorsList as $errorField) {
                    foreach ($errorField as $error ) { ?>
                        <li><?= htmlspecialchars($error) ?></li>
                    <?php }
                } ?>
            </ul>
        </div>
        <?php endif ?>
    </fieldset>
</form>

<?php $content = ob_get_clean(); 

require 'public/views/template.phtml'; ?>