<?php

$title = "Modifier un billet-Le café du Dev";

ob_start(); ?>

<form action="index.php?action=editPost&id=<?=$_GET['id']?>" method="POST">
    <fieldset>
        <legend>Modifier un billet</legend>
        <p>
            <label for="title">Titre</label>
            <input type="text" id='title' name='title' value="<?= $post[0]->title ?? '' ?>"
        </p>
        <p>
            <label for="post"></label>
            <textarea name="post" id="post"><?= $post[0]->post ?? "" ?> </textarea>
        </p>
        <input type="submit">
        
        <!-- ERRORS -->
        <?php 
            if ( isset($_SESSION['userEditPost']['errors']) ) : 
            $errorsList = $_SESSION['userEditPost']['errors'];
        ?>
        <div class="popup_error_form">
            <span>Envoi impossible veuillez vérifier les champs suivants :
            </span>
            <ul>
                <?php 
                foreach ($errorsList as $errorField) {
                    foreach ($errorField as $error ) { ?>
                        <li><?= htmlspecialchars($error) ?></li>
                    <?php }
                }
                unset($_SESSION['userEditPost']['errors']);
                ?>
            </ul>
        </div>
        <?php endif ?>
    </fieldset>
</form>

<?php $content = ob_get_clean(); 

require 'public/views/template.phtml'; ?>